language: node_js
node_js: 13
stages:
  #- lint
  #- unit
  - e2e
services:
  - docker
jobs:
  include:
    - stage: lint
      install: 
        - cd js-backend
        - npm install
      script:
        - npm run lint
    - stage: lint
      install: 
        - cd vue-ui
        - npm install
      script:
        - npm run lint
    - stage: unit
      install: 
        - cd vue-ui
        - npm install
      script:
        - npm run test:unit
    - stage: unit
      install: 
        - cd js-backend
        - npm install
      script:
        - npm run test:unit
    - stage: e2e
      script:
        - docker --version
        - docker-compose --version
        - chmod -R 775 .
        - npm run docker:e2e