version: '3.7'

services:
  # Emulate database
  database:
    image: mysql:5
    volumes:
      - ./owasp_sso.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./cache/database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: insecure-default-root-password
      MYSQL_DATABASE: owasp_sso
      MYSQL_USER: owasp_sso
      MYSQL_PASSWORD: insecure-default-password
    ports:
      - 3306:3306
  
  # Emulate SMTP
  smtp:
    image: mailhog/mailhog
    restart: always
    ports:
      - 8025:8025

  # Emulate syslog server for the central SIEM
  # Run it alone like this: docker run --name rsyslog.service -h test-host -p 514:514 jumanjiman/rsyslog
  # You can test payloads like here: https://superuser.com/a/1229424/497745
  # It is not enabled by default, as the website does not fully work if the server does not exist.
  # You need to enable this manually in to websites.json
  default-siem:
    image: jumanjiman/rsyslog
    hostname: default-siem
    restart: always